apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-settings
data:
  FORGEJO_INSTANCE_URL: https://forgejo.example.com
  FORGEJO_REPOSITORY_ALLOWLIST: |
    example/example
  FORGEJO_RUNNER_NAME: kubernetes-ephemeral
  FORGEJO_RUNNER_LABELS: linux-amd64:host
  RUNNER_IMAGE: forgejo-ephemeral-runner:dev
  LEADER_ELECTION_LEASE_NAME: forgejo-ephemeral-runner-controller
  METRICS_LISTEN_ADDRESS: ":9090"
  MAX_CONCURRENT: "1"
  RUNNER_STARTUP_TIMEOUT: 30m
  RUNNER_UNKNOWN_TIMEOUT: 5m
