apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-runner-controller
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-runner-job
automountServiceAccountToken: false
