apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: forgejo-e2e
spec:
  selector:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 3000
      targetPort: http
    - name: e2e-proxy
      port: 3001
      targetPort: e2e-proxy
